// Master job list powering the programmatic /resume-examples/{slug} pages.
// Each entry carries genuinely unique content so pages aren't thin duplicates
// (the #1 reason programmatic SEO fails). Category enables hub cross-linking.

export interface JobData {
  slug: string;
  title: string;
  category: string;
  salary: string;        // rough global range for the intro
  demand: string;        // one line on market demand
  atsKeywords: string[]; // the exact terms ATS scans for this role
  skills: string[];      // hard + soft skills
  summary: string;       // an example professional summary
  bullets: string[];     // example quantified experience bullets
  certs: string[];       // relevant certifications
  mistake: string;       // a common resume mistake for this role
}

export const JOBS: JobData[] = [
  {
    slug: "software-engineer", title: "Software Engineer", category: "Technology",
    salary: "$95,000–$160,000 (SAR 180k–420k in KSA)",
    demand: "Among the most in-demand roles globally and a Vision 2030 priority in Saudi Arabia's tech sector.",
    atsKeywords: ["JavaScript", "Python", "React", "Node.js", "REST API", "SQL", "Git", "CI/CD", "AWS", "microservices", "Agile", "unit testing"],
    skills: ["System design", "Data structures & algorithms", "Cloud (AWS/Azure)", "Docker & Kubernetes", "Code review", "Problem-solving", "Cross-functional collaboration"],
    summary: "Software Engineer with 5+ years building scalable web applications in React and Node.js. Shipped features serving 100k+ users and cut API latency 35% through query optimization and caching.",
    bullets: ["Architected a microservices backend that scaled to 1M requests/day with 99.9% uptime", "Reduced page-load time 40% by code-splitting and lazy-loading the React front end", "Mentored 3 junior engineers and introduced a code-review process that cut production bugs 25%"],
    certs: ["AWS Certified Developer", "Oracle Certified Java Programmer", "Certified Kubernetes Application Developer (CKAD)"],
    mistake: "Listing every technology you've ever touched instead of the specific stack in the job posting — ATS ranks focused, keyword-matched resumes higher.",
  },
  {
    slug: "registered-nurse", title: "Registered Nurse", category: "Healthcare",
    salary: "$60,000–$95,000 (SAR 120k–260k in KSA)",
    demand: "Persistent global shortage; major hiring across Saudi hospitals and the Red Sea/NEOM health projects.",
    atsKeywords: ["patient care", "BLS", "ACLS", "EMR", "medication administration", "triage", "vital signs", "care plans", "HIPAA", "infection control"],
    skills: ["Patient assessment", "IV therapy", "Electronic Medical Records (EMR)", "Wound care", "Patient education", "Empathy", "Time management under pressure"],
    summary: "Registered Nurse with 6 years in acute-care settings, managing up to 8 patients per shift while maintaining a 98% patient-satisfaction score and zero medication errors.",
    bullets: ["Managed care for 8+ acute patients per shift, coordinating with physicians to improve discharge times 20%", "Trained 5 new nurses on EMR charting and infection-control protocols", "Reduced patient falls 30% by implementing a hourly-rounding checklist"],
    certs: ["BLS", "ACLS", "Registered Nurse (RN) License", "SCFHS classification (for KSA)"],
    mistake: "Omitting license numbers, certifications (BLS/ACLS), and the EMR systems you know — these are the exact terms healthcare ATS filters scan for.",
  },
  {
    slug: "accountant", title: "Accountant", category: "Finance",
    salary: "$55,000–$90,000 (SAR 100k–240k in KSA)",
    demand: "Steady demand across every industry; Saudi VAT and Zakat regulations increase need for qualified accountants.",
    atsKeywords: ["accounts payable", "accounts receivable", "general ledger", "reconciliation", "financial reporting", "GAAP", "IFRS", "Excel", "SAP", "QuickBooks", "VAT", "auditing"],
    skills: ["Financial statement preparation", "Month-end close", "Budgeting & forecasting", "Tax compliance (VAT/Zakat)", "ERP systems (SAP/Oracle)", "Attention to detail", "Analytical thinking"],
    summary: "Detail-oriented Accountant with 5 years managing full-cycle accounting for firms up to $20M revenue. Cut month-end close from 10 to 6 days and recovered $120k in mis-billed receivables.",
    bullets: ["Managed general ledger and reconciled 15+ accounts monthly with 100% accuracy", "Prepared IFRS-compliant financial statements and supported a clean external audit", "Automated AP workflow in SAP, reducing invoice-processing time 45%"],
    certs: ["CPA", "CMA", "ACCA", "SOCPA (for KSA)"],
    mistake: "Writing 'responsible for accounting' instead of quantifying — recruiters and ATS both reward numbers like '$20M revenue' or 'reduced close by 4 days'.",
  },
  {
    slug: "project-manager", title: "Project Manager", category: "Business",
    salary: "$80,000–$130,000 (SAR 180k–360k in KSA)",
    demand: "Critical across construction, IT, and Saudi giga-projects (NEOM, Qiddiya, Red Sea).",
    atsKeywords: ["project management", "Agile", "Scrum", "stakeholder management", "budget management", "risk management", "Gantt", "PMP", "JIRA", "scope", "deliverables", "KPIs"],
    skills: ["Project planning & scheduling", "Budget & resource management", "Risk mitigation", "Stakeholder communication", "Agile & Waterfall", "Leadership", "Negotiation"],
    summary: "PMP-certified Project Manager who has delivered 20+ projects up to $5M on time and under budget, leading cross-functional teams of up to 15 across IT and construction.",
    bullets: ["Delivered a $5M ERP rollout 2 weeks early and 8% under budget across 4 departments", "Cut project risk by building a mitigation register that reduced schedule slippage 30%", "Led a 15-person cross-functional team using Agile, improving on-time delivery from 70% to 95%"],
    certs: ["PMP", "PRINCE2", "Certified ScrumMaster (CSM)", "CAPM"],
    mistake: "Describing tasks instead of outcomes — lead with budgets managed, timelines hit, and team sizes, then quantify the result.",
  },
  {
    slug: "data-analyst", title: "Data Analyst", category: "Technology",
    salary: "$65,000–$110,000 (SAR 140k–320k in KSA)",
    demand: "Explosive demand as Saudi organizations pursue data-driven Vision 2030 transformation.",
    atsKeywords: ["SQL", "Python", "Excel", "Power BI", "Tableau", "data visualization", "data cleaning", "statistics", "dashboards", "ETL", "A/B testing", "reporting"],
    skills: ["SQL querying", "Data visualization (Power BI/Tableau)", "Python/pandas", "Statistical analysis", "Dashboard design", "Business acumen", "Storytelling with data"],
    summary: "Data Analyst with 4 years turning raw data into decisions using SQL, Python, and Power BI. Built dashboards that cut reporting time 60% and surfaced a churn driver that saved $200k/year.",
    bullets: ["Built 10+ automated Power BI dashboards, reducing manual reporting 60%", "Wrote complex SQL to analyze 5M+ rows and identify a churn driver worth $200k annually", "Ran A/B tests that lifted email conversion 18%"],
    certs: ["Google Data Analytics Certificate", "Microsoft Power BI Data Analyst (PL-300)", "Tableau Desktop Specialist"],
    mistake: "Listing tools without impact — pair each tool ('SQL', 'Power BI') with a business result it produced.",
  },
  {
    slug: "business-analyst", title: "Business Analyst", category: "Business",
    salary: "$70,000 - $110,000 per year (SAR 262,500 - SAR 412,500)",
    demand: "High demand in KSA due to Saudi Vision 2030 driving business transformation projects.",
    atsKeywords: ["Business Analysis", "Requirements Gathering", "Stakeholder Management", "SWOT Analysis", "Process Improvement", "Project Management Tools", "Data Analysis", "Agile Methodologies", "TOGAF", "JIRA", "Power BI"],
    skills: ["Data-Driven Decision Making", "Communication", "Project Management", "Business Process Modeling", "Financial Analysis", "Change Management", "SQL"],
    summary: "Results-driven Business Analyst with 8+ years of experience, delivering projects that drive 20%+ operational efficiency. Proven track record of successfully bridging business and technology teams.",
    bullets: ["Analyzed market trends for a retail client, informing a strategic pivot that increased sales by 15% within 6 months.", "Designed and implemented process improvements for a banking institution, reducing operational costs by $500,000 annually.", "Led cross-functional teams in the implementation of a new CRM system, achieving 99% user adoption rate."],
    certs: ["CBAP (Certified Business Analysis Professional)", "PMP (Project Management Professional)", "PRINCE2", "ITIL Foundation"],
    mistake: "Including overly technical jargon without explaining business value impact.",
  },
  {
    slug: "sales-representative", title: "Sales Representative", category: "Business",
    salary: "$40,000 - $80,000 per year (SAR 150,000 - 300,000)",
    demand: "High demand in KSA driven by Saudi Vision 2030's economic diversification goals.",
    atsKeywords: ["CRM Software", "SalesForce", "Negotiation", "Market Research", "B2B Sales", "Revenue Growth", "Customer Acquisition", "Sales Analytics"],
    skills: ["Strategic Planning", "Data Analysis", "Public Speaking", "Team Leadership", "Adaptability", "Financial Literacy", "Arabic Language"],
    summary: "Results-driven Sales Representative with 5+ years of experience, achieving 25% annual revenue growth through targeted sales strategies. Proven track record of exceeding quarterly targets by 15% on average.",
    bullets: ["Increased sales in the KSA market by 30% within 6 months through effective market analysis.", "Successfully managed a portfolio of 50+ clients, ensuring a 95% retention rate.", "Implemented a new sales approach, reducing customer acquisition time by 40%."],
    certs: ["Certified Sales Professional (CSP)", "Sales Management Certification (SMC)", "HubSpot Sales Certification", "Google Analytics Certification"],
    mistake: "Including generic, unquantified statements (e.g., 'increased sales' without specifying the percentage or amount).",
  },
  {
    slug: "customer-service-representative", title: "Customer Service Representative", category: "Business",
    salary: "$35,000 - $50,000 per year (SAR 131,250 - SAR 187,500)",
    demand: "High demand in KSA due to Saudi Vision 2030's focus on service sector growth.",
    atsKeywords: ["Zendesk", "Customer Service Software", "Multilingual", "CRM Systems", "Conflict Resolution", "Time Management", "Team Collaboration", "Call Center Operations", "Customer Retention Strategies"],
    skills: ["Bilingual (Arabic/English)", "CRM Software", "Conflict Resolution", "Time Management", "Team Collaboration", "Call Center Experience", "Customer Retention Strategies"],
    summary: "Dedicated Customer Service Representative with 5+ years of experience, achieving 95% customer satisfaction rate. Proven track record of resolving 85% of customer complaints on the first call.",
    bullets: ["Handled an average of 200 calls/month, reducing resolution time by 30%", "Increased customer retention by 25% through personalized support", "Collaborated with a team to implement a new CRM, boosting efficiency by 40%"],
    certs: ["Certified Customer Service Representative (CCSR)", "FirstPoint Contact Center Certification", "Zendesk Certification"],
    mistake: "Including irrelevant hobbies instead of highlighting relevant tools or certifications",
  },
  {
    slug: "administrative-assistant", title: "Administrative Assistant", category: "Business",
    salary: "SAR 60,000 - 90,000 per year (USD 16,000 - 24,000)",
    demand: "High demand in KSA due to Saudi Vision 2030 driving business growth, increasing need for efficient Administrative Assistants.",
    atsKeywords: ["Microsoft Office", "Google Workspace", "Calendar Management", "Travel Arrangement", "Data Entry", "Customer Service", "Time Management", "ERP Systems"],
    skills: ["Proficient in Microsoft Office Suite", "Excellent Communication Skills", "Strong Organizational Abilities", "Basic Accounting Knowledge", "Fluent in Arabic & English", "Adaptability", "Problem Solving"],
    summary: "Dedicated Administrative Assistant with 5 years of experience, supporting up to 10 executives simultaneously, achieving a 95% on-time meeting schedule rate. Proven track record of reducing operational costs by 15% through process optimization.",
    bullets: ["Coordinated travel for 50+ executives annually, saving SAR 20,000 through negotiated rates.", "Managed a database of 2,000 contacts, ensuring 99% data accuracy.", "Implemented a filing system, reducing document retrieval time by 40%."],
    certs: ["Certified Administrative Professional (CAP)", "Microsoft Office Specialist (MOS)", "Certified Professional in Learning and Performance (CPLP)"],
    mistake: "Including irrelevant hobbies instead of highlighting transferable skills.",
  },
  {
    slug: "marketing-manager", title: "Marketing Manager", category: "Marketing",
    salary: "$60,000 - $120,000 per year (SAR 225,000 - SAR 450,000)",
    demand: "High demand driven by Saudi Vision 2030's emphasis on digital transformation and marketing innovation.",
    atsKeywords: ["Marketing Automation", "SEO", "Google Analytics", "Social Media Ads", "Content Strategy", "CRM Software", "Data-Driven Marketing", "AB Testing"],
    skills: ["Digital Marketing", "Team Management", "Data Analysis", "Creative Thinking", "Project Planning", "Public Speaking", "Excel Proficiency"],
    summary: "Results-driven Marketing Manager with 8+ years of experience, driving a 30% increase in brand engagement through targeted campaigns. Proven track record of leading high-performing teams to achieve 25% above sales targets.",
    bullets: ["Increased website traffic by 40% in 6 months through SEO optimization and content marketing.", "Managed a team of 5 to launch a successful social media campaign, reaching 1.5 million impressions.", "Analyzed market trends to inform a product launch strategy, resulting in a 20% market share gain."],
    certs: ["Google Analytics Certification", "HubSpot Inbound Marketing", "Facebook Blueprint Certification", "AGILE Project Management"],
    mistake: "Failing to quantify achievements with specific metrics and percentages.",
  },
  {
    slug: "human-resources-manager", title: "Human Resources Manager", category: "Business",
    salary: "$60,000 - $90,000 USD per year (approx. SAR 225,000 - 337,500 per year)",
    demand: "High demand for HR Managers in KSA, aligned with Saudi Vision 2030's labor market development goals.",
    atsKeywords: ["HRIS Systems", "Talent Acquisition", "Labor Law Compliance", "Performance Management", "SuccessFactors", "Workday", "Recruitment Marketing", "Diversity & Inclusion Strategies"],
    skills: ["Strategic Planning", "HRIS Management", "Leadership", "Communication", "Analytical Thinking", "Conflict Resolution", "Saudi Labor Laws"],
    summary: "Results-driven HR Manager with 8+ years of experience, improved employee retention by 25% through tailored engagement strategies. Proven track record of implementing efficient HR processes, reducing operational costs by 18%.",
    bullets: ["Designed and executed a diversity hiring program, increasing female workforce by 30% in 12 months.", "Implemented an automated HRIS system, reducing recruitment time by 40% and increasing data accuracy by 95%.", "Developed and led a leadership training program, resulting in a 22% increase in internal promotions."],
    certs: ["SHRM Certified Professional (SHRM-CP)", "Certified HR Professional (CHRP)", "Saudi Labor Law Certification", "CIPD Certificate in HR Management"],
    mistake: "Including generic responsibilities without quantifiable achievements or impact.",
  },
  {
    slug: "graphic-designer", title: "Graphic Designer", category: "Design",
    salary: "$50,000 - $80,000 per year (SAR 187,500 - 300,000)",
    demand: "High demand in KSA due to Saudi Vision 2030 driving digital transformation and creative industry growth.",
    atsKeywords: ["Adobe Creative Suite", "Sketch", "Figma", "UI/UX Design", "Branding", "Illustrator", "Photoshop", "InDesign", "Canva"],
    skills: ["Proficiency in Adobe Creative Suite", "Strong UI/UX Design Principles", "Effective Communication", "Project Management", "Branding Strategy", "Team Collaboration", "Analytical Thinking"],
    summary: "Results-driven Graphic Designer with 5+ years of experience, delivering projects with a 25% increase in client engagement through visually appealing designs. Proven track record of successfully leading design teams to meet tight deadlines.",
    bullets: ["Designed and implemented a rebranding campaign for a Saudi startup, resulting in a 30% boost in brand recognition.", "Created interactive UI/UX designs for a mobile app, achieving a 95% user satisfaction rate.", "Managed a team of 4 designers, completing projects 15% ahead of schedule."],
    certs: ["Adobe Certified Expert (ACE) - Graphic Design", "Certified UI/UX Designer", "Google Analytics Certification", "HubSpot Design Certification"],
    mistake: "Not including specific metrics to quantify the impact of design work in the experience section.",
  },
  {
    slug: "teacher", title: "Teacher", category: "Education",
    salary: "$40,000 - $80,000 / year (SAR 150,000 - 300,000)",
    demand: "High demand in KSA due to Saudi Vision 2030's education reforms",
    atsKeywords: ["Teaching Certification", "Lesson Planning", "Classroom Management", "Educational Technology", "Curriculum Development", "Special Needs Experience", "Assessment Strategies", "Bilingual (Arabic/English)"],
    skills: ["Lesson Planning", "Classroom Management", "Educational Technology Integration", "Bilingual Communication", "Adaptive Instruction", "Data-Driven Instruction", "Conflict Resolution"],
    summary: "Dedicated Teacher with 8 years of experience, achieving a 25% increase in student pass rates through innovative lesson plans. Proven track record of successfully integrating technology to enhance student engagement.",
    bullets: ["Taught 120 students across 4 grades, resulting in a 30% improvement in overall academic performance", "Developed and implemented a STEM curriculum, increasing student interest by 40%", "Collaborated with 15 teachers to design and execute a school-wide literacy program, boosting reading scores by 20%"],
    certs: ["Teaching Certification (KSA)", "TESOL Certification", "Special Education Certification", "Google for Education Certification"],
    mistake: "Including irrelevant hobbies instead of highlighting relevant teaching experience and certifications",
  },
  {
    slug: "civil-engineer", title: "Civil Engineer", category: "Engineering",
    salary: "$60,000 - $120,000 per year (SAR 225,000 - SAR 450,000)",
    demand: "High demand in KSA due to infrastructure projects aligned with Saudi Vision 2030.",
    atsKeywords: ["AutoCAD", "Revit", "STAAD Pro", "PMP", "Construction Management", "Geotechnical Engineering", "Building Information Modeling (BIM)", "Quality Assurance"],
    skills: ["Structural Analysis", "Project Management", "Communication", "Problem Solving", "Microsoft Office", "Team Leadership", "Data Analysis"],
    summary: "Results-driven Civil Engineer with 8 years of experience managing projects worth over $10M, achieving 95% on-time completion rate. Proven expertise in designing and developing sustainable infrastructure solutions.",
    bullets: ["Managed a team of 15 engineers on a $12M highway construction project, reducing costs by 12% through efficient resource allocation.", "Designed and implemented a water treatment plant serving 50,000 residents, exceeding quality standards by 15%.", "Conducted site inspections for a 20-story building project, ensuring 100% compliance with safety regulations."],
    certs: ["Professional Engineer (PE) License", "Project Management Professional (PMP)", "Certified Construction Manager (CCM)", "OSHA Certification"],
    mistake: "Including irrelevant hobbies instead of highlighting relevant technical skills and certifications.",
  },
  {
    slug: "mechanical-engineer", title: "Mechanical Engineer", category: "Engineering",
    salary: "$65,000 - $110,000 per year (SAR 244,000 - SAR 413,000)",
    demand: "High demand in KSA due to Saudi Vision 2030's infrastructure and industrial development goals.",
    atsKeywords: ["CATIA", "ANSI", "FEA", "PLM", "CAD Design", "Mechatronics", "Quality Control", "Lean Manufacturing", "Six Sigma", "API Standards"],
    skills: ["Mechanical Design", "Project Management", "Communication", "Problem Solving", "Team Leadership", "CAD/CAM", "Data Analysis"],
    summary: "Results-driven Mechanical Engineer with 8+ years of experience, delivering projects with up to 25% cost savings through optimization. Proven track record in leading cross-functional teams to achieve 99% project completion rate on time.",
    bullets: ["Designed and implemented a mechanical system upgrade, increasing plant efficiency by 30%.", "Managed a team of 5 engineers on a $2M project, completing 2 months ahead of schedule.", "Conducted failure analysis, reducing equipment downtime by 40% through targeted maintenance."],
    certs: ["PE License", "Certified Quality Engineer (CQE)", "Certified Lean Six Sigma Black Belt"],
    mistake: "Overemphasizing technical skills without highlighting achievements and impact on business outcomes.",
  },
  {
    slug: "electrical-engineer", title: "Electrical Engineer", category: "Engineering",
    salary: "$80,000 - $140,000 per year (SAR 300,000 - SAR 525,000)",
    demand: "High demand in KSA driven by Saudi Vision 2030's infrastructure development",
    atsKeywords: ["Electrical Engineering", "Power Systems", "Microcontrollers", "Circuit Analysis", "PLC Programming", "AutoCAD", "PMP", "IEC Standards", "ETAP", "Siemens SIMATIC"],
    skills: ["Circuit Design", "Project Management", "Team Leadership", "Problem-Solving", "Communication", "AutoCAD", "PMP Certification"],
    summary: "Results-driven Electrical Engineer with 8+ years of experience, delivering projects with 25% cost savings through optimized design. Proven expertise in power systems and microcontroller integration.",
    bullets: ["Designed and implemented a power distribution system for a Saudi industrial park, reducing energy losses by 18%", "Led a team of 5 engineers in the development of a smart building automation system, completing 3 months ahead of schedule", "Improved factory efficiency by 22% through the implementation of PLC-controlled manufacturing lines"],
    certs: ["PE License (Electrical)", "PMP Certification", "Siemens Certified Engineer", "NEC Code Compliance Specialist"],
    mistake: "Including irrelevant hobbies (e.g., 'chess player') instead of highlighting relevant tools or certifications",
  },
  {
    slug: "financial-analyst", title: "Financial Analyst", category: "Finance",
    salary: "$60,000 - $90,000 per year (SAR 225,000 - 337,500)",
    demand: "High demand in KSA due to Saudi Vision 2030 driving financial sector growth.",
    atsKeywords: ["Financial Modeling", "Excel VBA", "SQL", "Financial Planning", "Budgeting", "Forecasting", "GAAP", "Power BI", "Financial Analysis", "Investment Banking"],
    skills: ["Financial Analysis", "Data Visualization", "Communication", "Financial Modeling", "Time Management", "SQL", "Leadership"],
    summary: "Results-driven Financial Analyst with 5+ years of experience, delivering insights that drove 15% revenue growth through data-driven decisions. Proven expertise in financial planning and budgeting for multinational corporations.",
    bullets: ["Analyzed financial data for a Fortune 500 company, identifying $1M in cost savings opportunities.", "Developed and implemented financial models that increased forecasting accuracy by 20%.", "Managed a team of 3 analysts, enhancing project delivery time by 30%."],
    certs: ["CFA Charterholder", "CPA", "FRM", "Google Data Analytics Certification"],
    mistake: "Including irrelevant certifications (e.g., non-financial or outdated ones) that do not align with the Financial Analyst role.",
  },
  {
    slug: "product-manager", title: "Product Manager", category: "Technology",
    salary: "$85,000 - $120,000 per year (SAR 318,750 - SAR 450,000)",
    demand: "High demand for Product Managers in KSA, aligning with Saudi Vision 2030's digital transformation goals.",
    atsKeywords: ["Agile Methodologies", "Jira", "Product Roadmap", "Market Analysis", "Competitive Research", "User Story Mapping", "PMP", "Lean Startup", "Kanban", "OKRs"],
    skills: ["Strategic Planning", "Data-Driven Decision Making", "Stakeholder Management", "Communication", "Project Management", "Market Analysis", "Technical Acumen"],
    summary: "Results-driven Product Manager with 8+ years of experience, delivering a 30% revenue increase through data-driven product launches. Proven track record of aligning product strategies with business objectives.",
    bullets: ["Increased customer engagement by 25% through A/B testing and user feedback implementation.", "Successfully managed a cross-functional team to launch 3 products within 6 months, meeting 95% of roadmap milestones.", "Analyzed market trends, resulting in a 20% reduction in product development costs."],
    certs: ["MBA", "PMP Certification", "CSM (Certified Scrum Master)", "Google Analytics Certification"],
    mistake: "Not quantifying achievements in the work experience section.",
  },
  {
    slug: "operations-manager", title: "Operations Manager", category: "Business",
    salary: "$80,000 - $120,000 per year (SAR 300,000 - SAR 450,000)",
    demand: "High demand in KSA due to Saudi Vision 2030's emphasis on operational efficiency in growing industries.",
    atsKeywords: ["Operations Management", "Supply Chain Optimization", "ERP Systems", "Leadership", "Process Improvement", "Budgeting", "Project Management", "KPI Analysis"],
    skills: ["Strategic Planning", "Team Leadership", "Supply Chain Management", "Financial Analysis", "Communication", "Problem Solving", "Adaptability"],
    summary: "Results-driven Operations Manager with 8+ years of experience, achieving a 25% reduction in operational costs through process optimization. Proven track record in leading high-performing teams.",
    bullets: ["Managed a team of 15, increasing productivity by 30% through targeted training.", "Implemented ERP system, reducing inventory costs by 22% within 6 months.", "Developed and executed a budget plan, resulting in a 15% surplus."],
    certs: ["PMP Certification", "APICS CPIM", "Lean Six Sigma Black Belt", "Prince2 Practitioner"],
    mistake: "Listing responsibilities without quantifying achievements.",
  },
  {
    slug: "web-developer", title: "Web Developer", category: "Technology",
    salary: "$60,000 - $120,000 (SAR 225,000 - SAR 450,000) annually",
    demand: "High demand for Web Developers in KSA, aligned with Saudi Vision 2030's digital transformation goals.",
    atsKeywords: ["ReactJS", "Node.js", "AWS", "Agile", "Git", "HTML5", "CSS3", "MySQL"],
    skills: ["Proficient in JavaScript", "Strong Problem Solving", "Team Collaboration", "Responsive Web Design", "API Integration", "Version Control", "Adaptability"],
    summary: "Results-driven Web Developer with 5+ years of experience, delivering projects with 25% average timeline reduction. Proficient in building scalable web applications.",
    bullets: ["Developed a responsive e-commerce site for a KSA retail client, increasing sales by 18%", "Improved website load time by 40% for a Riyadh-based startup through optimization", "Led a team of 3 to launch a government portal, achieving 99.9% uptime in the first quarter"],
    certs: ["Certified Web Developer (CWD)", "AWS Certified Developer", "Google Analytics Certification", "Scrum Master Certification"],
    mistake: "Including irrelevant hobbies instead of highlighting relevant tools or certifications",
  },
  {
    slug: "devops-engineer", title: "DevOps Engineer", category: "Technology",
    salary: "$80,000 - $140,000/year (SAR 300,000 - 525,000/year)",
    demand: "High demand for DevOps Engineers in KSA, driven by Saudi Vision 2030's digital transformation goals.",
    atsKeywords: ["AWS", "CI/CD", "Kubernetes", "Docker", "Ansible", "Jenkins", "GitOps", "Infrastructure-as-Code"],
    skills: ["Cloud Migration", "Containerization", "Agile Methodologies", "Python", "Collaboration", "Problem-Solving", "Monitoring & Logging"],
    summary: "Results-driven DevOps Engineer with 5+ years of experience, achieving 99.9% uptime in cloud infrastructure. Proven track record of reducing deployment time by 40% through automation.",
    bullets: ["Automated 90% of deployment pipeline using Jenkins and Ansible, cutting release time by 30 days", "Designed and implemented a Kubernetes cluster on AWS, handling 10,000+ concurrent users", "Improved system reliability by 25% through proactive monitoring with Prometheus and Grafana"],
    certs: ["AWS Certified DevOps Engineer", "Kubernetes Certified Administrator", "ITIL Foundation Certificate", "Google Cloud Certified - Professional Cloud Developer"],
    mistake: "Overemphasizing technical tools without highlighting the business value and impact of DevOps practices.",
  },
  {
    slug: "cybersecurity-analyst", title: "Cybersecurity Analyst", category: "Technology",
    salary: "$80,000 - $120,000 per year (SAR 300,000 - SAR 450,000)",
    demand: "High demand in KSA driven by Saudi Vision 2030's emphasis on digital transformation and cybersecurity.",
    atsKeywords: ["CompTIA Security+", "CISSP", "NIST Framework", "Threat Intelligence", "Incident Response", "SIEM Tools", "AWS Security"],
    skills: ["Network Security", "Threat Analysis", "Communication", "Cloud Security (AWS)", "Python Scripting", "Team Leadership", "Risk Assessment"],
    summary: "Proven Cybersecurity Analyst with 5+ years of experience, having reduced security breaches by 30% through enhanced monitoring. Skilled in designing and implementing robust security protocols.",
    bullets: ["Analyzed and mitigated 250+ potential threats monthly using SIEM tools, ensuring 99.9% system uptime.", "Designed and implemented a cloud security framework for AWS, reducing costs by 25%.", "Led a team to achieve 100% compliance with NIST Framework within 6 months."],
    certs: ["CompTIA Security+", "CISSP", "CEH", "AWS Certified Security - Specialty"],
    mistake: "Listing generic responsibilities without quantifying achievements or impact.",
  },
  {
    slug: "network-engineer", title: "Network Engineer", category: "Technology",
    salary: "$80,000 - $120,000 per year (SAR 300,000 - SAR 450,000)",
    demand: "High demand driven by Saudi Vision 2030's digital transformation initiatives.",
    atsKeywords: ["Cisco CCNA", "Network Architecture", "SD-WAN", "AWS Networking", "BGP", "Cisco Nexus", "VMware NSX", "ITIL", "Juniper JNAP", "MPLS"],
    skills: ["Network Protocol Design", "Cloud Migration", "Team Leadership", "Troubleshooting", "Python Scripting", "Agile Methodologies", "Cyber Security Basics"],
    summary: "Results-driven Network Engineer with 8+ years of experience, delivering 99.99% network uptime across global infrastructures. Proven track record of reducing network latency by 30% through optimization.",
    bullets: ["Designed and implemented a SD-WAN solution for a Fortune 500 company, resulting in 25% cost savings.", "Managed a team of 5 engineers to deploy a Cisco-based network infrastructure for a new data center, completing 2 weeks ahead of schedule.", "Resolved a critical network outage affecting 10,000 users, restoring full connectivity within 4 hours."],
    certs: ["Cisco Certified Network Professional (CCNP)", "CompTIA Security+", "AWS Certified Solutions Architect - Associate", "ITIL Foundation"],
    mistake: "Including irrelevant technical skills not aligned with the Network Engineer role, such as web development frameworks.",
  },
  {
    slug: "pharmacist", title: "Pharmacist", category: "Healthcare",
    salary: "$60,000 - $120,000 per year (SAR 225,000 - SAR 450,000)",
    demand: "High demand in KSA, aligned with Saudi Vision 2030's healthcare expansion goals.",
    atsKeywords: ["Pharmacy Management Software", "Medication Therapy Management", "PharmD", "Saudi Pharmacy License", "Clinical Pharmacy", "Inventory Control Systems", "Patient Counseling", "HL7 Compliance", "EHR Systems", "Quality Assurance"],
    skills: ["Clinical Decision Making", "Patient Communication", "Pharmacy Software", "Leadership", "Time Management", "Pharmacotherapy", "Data Analysis"],
    summary: "Dedicated Pharmacist with 8+ years of experience, achieving 25% reduction in medication errors through process improvements. Proven track record of successfully managing pharmacy teams.",
    bullets: ["Managed a team of 5 pharmacists, increasing patient satisfaction ratings by 30% through enhanced counseling services.", "Implemented inventory control system, reducing stockouts by 40% and saving SAR 150,000 annually.", "Conducted 500+ medication therapy management sessions, resulting in a 20% decrease in hospital readmissions."],
    certs: ["Saudi Pharmacy License", "ACCP Certification", "CPR Certification", "Pharmacy Informatics Certification"],
    mistake: "Including irrelevant certifications not recognized by the Saudi Commission for Health Specialties.",
  },
  {
    slug: "medical-assistant", title: "Medical Assistant", category: "Healthcare",
    salary: "$40,000 - $65,000/year (SAR 150,000 - 245,000/year)",
    demand: "High demand in KSA due to Saudi Vision 2030's healthcare expansion goals.",
    atsKeywords: ["EMR Systems", "Phlebotomy", "CPR Certified", "Medical Terminology", "EKG Interpretation", "HIPAA Compliance", "Electronic Charting"],
    skills: ["Clinical Assessment", "Phlebotomy", "EMR Software", "Patient Communication", "Time Management", "Anatomy Knowledge", "Basic Life Support"],
    summary: "Dedicated Medical Assistant with 5+ years of experience, having improved patient satisfaction by 25% through efficient workflow management. Proficient in both clinical and administrative tasks.",
    bullets: ["Assisted in 500+ patient exams, maintaining a 98% patient satisfaction rate.", "Performed 2000+ phlebotomy procedures with 100% accuracy.", "Reduced clinic wait times by 30% through process optimization."],
    certs: ["CMA (Certified Medical Assistant)", "CPR/First Aid Certification", "EMR Certification", "Phlebotomy Certification"],
    mistake: "Including irrelevant non-medical work experience in excess of relevant medical experience.",
  },
  {
    slug: "receptionist", title: "Receptionist", category: "Business",
    salary: "KSA: 4,000 - 6,000 SAR/month, Global: $1,000 - $1,500/month",
    demand: "High demand in KSA due to Saudi Vision 2030 driving business growth, increasing need for skilled Receptionists",
    atsKeywords: ["Receptionist Software", "MS Office", "Multilingual", "Customer Service", "Scheduling Tools", "Phone Systems", "Time Management"],
    skills: ["Bilingual (Arabic/English)", "MS Office Proficiency", "Customer Service", "Time Management", "Multitasking", "Basic Accounting", "Conflict Resolution"],
    summary: "Dedicated Receptionist with 5+ years of experience managing front-desk operations, achieving 99% customer satisfaction rate. Proven track record of efficiently handling 200+ daily calls and inquiries",
    bullets: ["Handled 250 daily calls, reduced wait time by 30% through process optimization", "Managed scheduling for 50+ employees, ensuring 95% meeting punctuality", "Increased client satisfaction ratings by 25% through personalized service delivery"],
    certs: ["Certified Administrative Professional (CAP)", "Certified Receptionist (CR)", "First Aid Certification", "Basic Life Support (BLS)"],
    mistake: "Including irrelevant hobbies instead of highlighting relevant software proficiency or language skills",
  },
  {
    slug: "digital-marketing-specialist", title: "Digital Marketing Specialist", category: "Marketing",
    salary: "$50,000 - $80,000 per year (SAR 187,500 - 300,000)",
    demand: "High demand in KSA due to Saudi Vision 2030's digital transformation drive.",
    atsKeywords: ["Google Analytics", "Facebook Ads", "SEO", "PPC", "Content Marketing", "Email Marketing", "HubSpot", "Google Ads", "Social Media Management", "Marketing Automation"],
    skills: ["Data Analysis", "Content Creation", "Team Collaboration", "SEO Optimization", "Paid Advertising", "Social Media Management", "Project Management"],
    summary: "Results-driven Digital Marketing Specialist with 5+ years of experience, delivering up to 30% increase in website traffic through targeted campaigns. Proven track record in boosting social media engagement by 50%.",
    bullets: ["Increased brand awareness by 25% through strategic social media campaigns.", "Improved website conversion rates by 20% via A/B testing and SEO.", "Managed $10,000 monthly ad spend, achieving a 300% ROI."],
    certs: ["Google Analytics Certification", "Facebook Blueprint Certification", "HubSpot Inbound Marketing Certification", "SEO Certification by Moz"],
    mistake: "Not quantifying achievements with specific metrics in experience section.",
  },
  {
    slug: "ux-ui-designer", title: "UX UI Designer", category: "Design",
    salary: "$60,000 - $120,000 per year (SAR 225,000 - SAR 450,000)",
    demand: "High demand for UX UI Designers in KSA, driven by Saudi Vision 2030's digital transformation initiatives.",
    atsKeywords: ["Figma", "Sketch", "Adobe XD", "User Research", "Wireframing", "Prototyping", "Accessibility Design", "Interaction Design"],
    skills: ["Proficient in Design Systems", "Strong User-Centered Design Approach", "Effective Communication", "Collaborative Teamwork", "Analytical Problem Solving", "Adaptability to Feedback", "Basic Coding Principles (HTML/CSS)"],
    summary: "Results-driven UX UI Designer with 5+ years of experience, improving user engagement by 30% through data-driven design. Proficient in creating seamless, accessible interfaces for web and mobile applications.",
    bullets: ["Designed and implemented a mobile app UI for a fintech startup, resulting in a 25% increase in user retention.", "Conducted user research for an e-commerce platform, informing design decisions that led to a 20% boost in conversions.", "Created an accessible design system for a government website, achieving WCAG 2.1 compliance."],
    certs: ["Certified UX Designer (CUXD)", "Adobe Certified Expert - Adobe XD", "Google Analytics Certification", "Certified Accessibility Specialist (CAS)"],
    mistake: "Including generic, unquantified statements (e.g., 'Improved user experience') without specific metrics or outcomes.",
  },
  {
    slug: "full-stack-developer", title: "Full Stack Developer", category: "Technology",
    salary: "$80,000 - $140,000 per year (SAR 300,000 - SAR 525,000)",
    demand: "High demand for Full Stack Developers in KSA, driven by Saudi Vision 2030's digital transformation initiatives.",
    atsKeywords: ["React", "Node.js", "MongoDB", "AWS", "CI/CD", "RESTful APIs", "TypeScript", "Agile"],
    skills: ["Proficient in JavaScript", "Strong Problem Solving", "Experience with State Management", "Excellent Team Collaboration", "Familiarity with Cloud Deployments", "Understanding of Security Best Practices", "Adaptability"],
    summary: "Results-driven Full Stack Developer with 5+ years of experience, delivering projects with up to 30% increased efficiency through optimized code. Proficient in designing and developing scalable web applications.",
    bullets: ["Developed and deployed a React-based web app for a KSA startup, resulting in a 25% increase in user engagement.", "Improved API response time by 40% through optimization of Node.js backend for an e-commerce platform.", "Collaborated on an Agile team to deliver a MongoDB-powered project 2 weeks ahead of schedule."],
    certs: ["Certified Node.js Developer", "AWS Certified Developer - Associate", "React Certification (Pluralsight)"],
    mistake: "Not providing specific metrics or examples of project impact in the experience section.",
  },
  {
    slug: "data-scientist", title: "Data Scientist", category: "Technology",
    salary: "$80,000 - $140,000 per year (SAR 300,000 - SAR 525,000)",
    demand: "High demand in KSA driven by Saudi Vision 2030's digital transformation initiatives.",
    atsKeywords: ["Python", "TensorFlow", "Scikit-Learn", "Tableau", "SQL", "NoSQL", "AWS", "Azure ML", "Kaggle", "Jupyter Notebook"],
    skills: ["Python Programming", "Machine Learning", "Data Visualization", "Cloud Computing", "Communication", "Team Collaboration", "Statistical Analysis"],
    summary: "Results-driven Data Scientist with 5+ years of experience, delivering predictive models that drive business growth, e.g., a 25% sales increase through targeted marketing campaigns. Proficient in leveraging data insights to inform strategic decisions.",
    bullets: ["Developed and deployed a predictive maintenance model for a manufacturing client, reducing downtime by 30%.", "Analyzed customer purchase behavior, identifying a $1M revenue opportunity through targeted promotions.", "Led a team to build a real-time analytics dashboard, increasing data-driven decisions by 40%."],
    certs: ["Certified Data Scientist (CDS)", "Google Cloud Certified - Professional Data Engineer", "Microsoft Certified: Azure AI Engineer Associate", "Certified Analytics Professional (CAP)"],
    mistake: "Including irrelevant tools or technologies not directly applicable to the Data Scientist role, diluting the resume's focus.",
  },
  {
    slug: "executive-assistant", title: "Executive Assistant", category: "Business",
    salary: "$60,000 - $90,000 USD per year (SAR 225,000 - 337,500 per year)",
    demand: "High demand for Executive Assistants in KSA, driven by Saudi Vision 2030's emphasis on developing the private sector and increasing the need for high-level administrative support.",
    atsKeywords: ["Microsoft Office Suite", "Calendar Management", "Travel Arrangements", "Executive Support", "Discretion and Confidentiality", "Project Coordination", "Time Management", "Stakeholder Engagement"],
    skills: ["Advanced Microsoft Office", "Strategic Planning", "Effective Communication", "Time Management", "Problem Solving", "Cultural Awareness", "Digital Literacy"],
    summary: "Results-driven Executive Assistant with 8+ years of experience supporting C-level executives, achieving a 30% increase in executive productivity through optimized scheduling and task management. Proven track record of handling sensitive information with utmost discretion.",
    bullets: ["Coordinated executive travel arrangements for 50+ international trips annually, resulting in a 25% reduction in travel costs through negotiated vendor rates.", "Managed calendars for 3 C-suite executives, ensuring a 99% meeting attendance rate and facilitating seamless communication among teams.", "Implemented an electronic filing system, increasing document retrieval efficiency by 40% and enhancing data security."],
    certs: ["Certified Executive Assistant (CEA)", "Certified Administrative Professional (CAP)", "Project Management Professional (PMP)"],
    mistake: "Including overly generic phrases (e.g., 'proficient in Microsoft Office') without specifying the depth of skill or impact on productivity.",
  },
  {
    slug: "office-manager", title: "Office Manager", category: "Business",
    salary: "$50,000 - $80,000 per year (SAR 187,500 - SAR 300,000)",
    demand: "Office Manager roles are in high demand in KSA, particularly in sectors aligned with Saudi Vision 2030's economic diversification goals.",
    atsKeywords: ["MS Office Suite", "Staff Supervision", "Facilities Management", "Budgeting Software", "Time Management", "Conflict Resolution", "ERP Systems", "Compliance Management", "Supply Chain Coordination", "Leadership Development"],
    skills: ["Strategic Planning", "Financial Management", "Team Leadership", "Communication", "Problem Solving", "Adaptability", "Data Analysis"],
    summary: "Results-driven Office Manager with 8+ years of experience, overseeing teams of up to 15 members and achieving a 25% reduction in operational costs through process optimization. Proven track record of successfully managing multi-million SAR budgets.",
    bullets: ["Managed a team of 12, increasing productivity by 30% through targeted training and workflow streamlining.", "Successfully implemented a new inventory management system, reducing supply chain delays by 40%.", "Negotiated a 15% discount with a major supplier, saving SAR 120,000 annually."],
    certs: ["Certified Administrative Professional (CAP)", "Certified Office Manager (COM)", "Project Management Professional (PMP)", "LEED Accredited Professional"],
    mistake: "Failing to quantify achievements in the work experience section, e.g., not specifying the number of team members managed or the exact cost savings achieved.",
  },
  {
    slug: "construction-project-manager", title: "Construction Project Manager", category: "Engineering",
    salary: "$85,000 - $120,000 per year (SAR 319,500 - SAR 450,000)",
    demand: "High demand in KSA driven by Saudi Vision 2030 infrastructure projects.",
    atsKeywords: ["Primavera P6", "Construction Management Software", "LEED Certification", "Project Scheduling", "Budgeting", "Risk Management", "Saudi Building Code", "MS Project", "BIM", "Contract Administration"],
    skills: ["Project Planning", "Budget Control", "Team Leadership", "Risk Analysis", "Stakeholder Management", "Contract Negotiation", "Arabic Language"],
    summary: "Results-driven Construction Project Manager with 8+ years of experience delivering large-scale projects on time, achieving a 95% client satisfaction rate. Proven track record of reducing project costs by an average of 12% through efficient resource allocation.",
    bullets: ["Managed a $50M infrastructure project in Riyadh, completing 3 months ahead of schedule.", "Successfully reduced labor costs by 15% on a 500,000 sq.ft. commercial building project in Jeddah.", "Coordinated with 5+ subcontractors to deliver a residential complex in Dammam with zero safety incidents."],
    certs: ["PMP (Project Management Professional)", "LEED AP (Leadership in Energy & Environmental Design Accredited Professional)", "CCIM (Certified Construction Inspector Manager)"],
    mistake: "Including too broad or generic job responsibilities without quantifiable achievements.",
  },
  {
    slug: "petroleum-engineer", title: "Petroleum Engineer", category: "Engineering",
    salary: "$80,000 - $180,000 per year (SAR 300,000 - 675,000)",
    demand: "High demand driven by Saudi Vision 2030's energy sector investments.",
    atsKeywords: ["EOR Techniques", "Reservoir Simulation", "Well Design", "Drilling Engineering", "Petroleum Economics", "API Standards", "SCADA Systems", "Geological Modeling"],
    skills: ["Reservoir Engineering", "Drilling Operations", "Project Management", "Data Analysis", "Team Leadership", "Communication", "Geoscience Integration"],
    summary: "Results-driven Petroleum Engineer with 8+ years of experience, delivering a 15% increase in oil recovery through optimized EOR techniques. Proven track record in leading cross-functional teams for onshore/offshore projects.",
    bullets: ["Increased field production by 20% through reservoir modeling and simulation in Saudi Aramco's Khafji Field.", "Designed and implemented a drilling program reducing costs by $2M per well in a tight gas field.", "Improved HSE compliance by 30% through process safety audits and training initiatives."],
    certs: ["Professional Engineer (PE) License", "API Certification in Drilling Engineering", "Certified Petroleum Engineer (CPE)", "NEBOSH General Certificate in Occupational Health and Safety"],
    mistake: "Including irrelevant certifications not aligned with petroleum engineering best practices.",
  },
  {
    slug: "supply-chain-manager", title: "Supply Chain Manager", category: "Business",
    salary: "$80,000 - $120,000 per year (SAR 300,000 - SAR 450,000)",
    demand: "High demand driven by Saudi Vision 2030's industrialization goals, seeking Supply Chain Managers to optimize logistics.",
    atsKeywords: ["Supply Chain Optimization", "ERP Systems", "Inventory Management", "Global Sourcing", "Lean Manufacturing", "SCM Software", "Cost Reduction Strategies", "Vendor Management"],
    skills: ["Strategic Planning", "Data Analysis", "Leadership", "Negotiation", "Problem Solving", "Communication", "ERP Proficiency"],
    summary: "Results-driven Supply Chain Manager with 8+ years of experience, achieving a 25% reduction in supply chain costs through process optimization. Proven track record in managing global supply chains with a focus on efficiency and compliance.",
    bullets: ["Managed a supply chain worth $50M, reducing delays by 30% through timely vendor management.", "Implemented an ERP system, increasing inventory accuracy to 99% and cutting operational costs by 15%.", "Developed and executed a strategic sourcing plan, resulting in a 20% reduction in procurement costs."],
    certs: ["APICS CPIM", "CSCP", "CLTD", "Six Sigma Black Belt"],
    mistake: "Failing to quantify achievements in the experience section, e.g., just listing 'cost reduction' without specifying the percentage or amount saved.",
  },
  {
    slug: "hotel-manager", title: "Hotel Manager", category: "Hospitality",
    salary: "$50,000 - $80,000 per year (SAR 187,500 - 300,000)",
    demand: "High demand in KSA due to tourism growth aligned with Saudi Vision 2030",
    atsKeywords: ["PMS Software", "Revenue Management", "Hospitality CRM", "Multi-Unit Management", "Arabic Language", "Budgeting Tools", "OTA Management", "Staff Scheduling"],
    skills: ["Strategic Planning", "Multilingual (Arabic/English)", "Financial Analysis", "Leadership", "Customer Service", "Crisis Management", "Operational Efficiency"],
    summary: "Results-driven Hotel Manager with 8+ years of experience, achieving 25% increase in occupancy rates through targeted marketing strategies. Proven track record of reducing operational costs by 15% through efficient resource allocation.",
    bullets: ["Increased guest satisfaction ratings by 30% through staff training and feedback implementation", "Managed a team of 50, reducing turnover by 20% in one year", "Improved revenue by 18% through successful negotiation of corporate rates and OTA partnerships"],
    certs: ["Certified Hotel Administrator (CHA)", "Certified Hospitality Manager (CHM)", "PMP Certification", "First Aid Certification"],
    mistake: "Including irrelevant food service experience without highlighting transferable skills",
  },
  {
    slug: "ai-engineer", title: "AI Engineer", category: "Technology",
    salary: "$120,000 - $180,000 per year (SAR 450,000 - 675,000)",
    demand: "High demand for AI Engineers in KSA, driven by Saudi Vision 2030's digital transformation goals.",
    atsKeywords: ["TensorFlow", "PyTorch", "Computer Vision", "NLP", "AWS SageMaker", "Azure Machine Learning", "Scikit-learn", "Keras", "Docker", "Kubernetes"],
    skills: ["Python Programming", "Deep Learning", "Cloud Computing", "Team Collaboration", "Problem Solving", "Data Preprocessing", "Model Deployment"],
    summary: "Results-driven AI Engineer with 5+ years of experience, delivering projects with up to 30% accuracy improvement in predictive models. Proficient in designing and deploying scalable AI solutions.",
    bullets: ["Developed and deployed a computer vision model using TensorFlow, achieving 92% object detection accuracy for a retail client.", "Improved NLP chatbot response accuracy by 25% for a financial services firm using PyTorch and transformers.", "Designed and implemented an AI-powered recommendation system, increasing sales by 15% for an e-commerce platform."],
    certs: ["Google Cloud Certified - Professional Machine Learning Engineer", "Microsoft Certified: Azure AI Engineer Associate", "Certified Data Scientist - Data Science Council of America"],
    mistake: "Not providing specific metrics or examples of project outcomes in the experience section.",
  },
  {
    slug: "banking-analyst", title: "Banking Analyst", category: "Finance",
    salary: "$65,000 - $110,000 per year (SAR 244,000 - SAR 413,000)",
    demand: "High demand for Banking Analysts in KSA driven by Saudi Vision 2030's financial sector growth initiatives.",
    atsKeywords: ["Financial Modeling", "Risk Analysis", "SQL", "Python", "Excel VBA", "Financial Regulations", "Portfolio Management", "Data Visualization"],
    skills: ["Financial Analysis", "Data Interpretation", "Communication", "Problem-Solving", "Microsoft Office Suite", "Time Management", "Team Collaboration"],
    summary: "Results-driven Banking Analyst with 5+ years of experience, delivering 25%+ portfolio growth through data-driven insights. Proficient in financial modeling and risk assessment.",
    bullets: ["Analyzed market trends, resulting in a 30% reduction in investment risks for a major Saudi bank.", "Developed and implemented a financial forecasting model, improving accuracy by 22%.", "Collaborated with cross-functional teams to launch a new investment product, yielding a 15% increase in customer acquisitions."],
    certs: ["CFA Charterholder", "FRM Certification", "CIPM Certification", "ACCA Certification"],
    mistake: "Overemphasizing technical skills without providing quantifiable business outcomes.",
  },
  {
    slug: "safety-officer", title: "Safety Officer", category: "Engineering",
    salary: "$60,000 - $120,000 per year (SAR 225,000 - 450,000)",
    demand: "High demand in KSA due to Saudi Vision 2030's infrastructure development focus",
    atsKeywords: ["OSHA Certification", "HSE Management", "Risk Assessment", "Safety Auditing", "Compliance Enforcement", "Incident Investigation", "Ergonomics", "Emergency Response Planning", "HAZWOPER", "Construction Safety"],
    skills: ["HSE Management", "Risk Analysis", "Communication", "Audit & Compliance", "Leadership", "Data Analysis", "Emergency Response"],
    summary: "Results-driven Safety Officer with 8+ years of experience ensuring 100% compliance with OSHA standards across multiple construction sites, achieving a 40% reduction in workplace incidents. Proven track record of implementing effective safety protocols that enhance operational efficiency.",
    bullets: ["Ensured 0 lost-time incidents over 3 years at a large construction site with 500+ workers", "Developed and implemented a safety training program, increasing employee certification rates by 90%", "Conducted 200+ safety audits, identifying and mitigating 95% of potential hazards before incidents occurred"],
    certs: ["OSHA 30-Hour Construction Safety Certification", "NEBOSH General Certificate in Occupational Health and Safety", "CSP (Certified Safety Professional)"],
    mistake: "Failing to quantify safety achievements (e.g., omitting incident reduction percentages or numbers)",
  },
  {
    slug: "quantity-surveyor", title: "Quantity Surveyor", category: "Engineering",
    salary: "$60,000 - $120,000 per year (SAR 225,000 - SAR 450,000)",
    demand: "High demand in KSA due to infrastructure projects aligned with Saudi Vision 2030",
    atsKeywords: ["Quantity Surveying", "RICS", "QS Software", "Construction Budgeting", "Tender Management", "BOQ", "Cost Engineering", "BIM", "Autodesk", "Primavera"],
    skills: ["Cost Estimation", "Contract Administration", "Project Management", "Communication", "Analytical Thinking", "MS Office", "Team Leadership"],
    summary: "Results-driven Quantity Surveyor with 8+ years of experience delivering construction projects 15% under budget on average. Proven track record in managing teams and negotiating contracts with a 90% success rate.",
    bullets: ["Managed a team of 5 QSs on a $10M infrastructure project, achieving 12% cost savings", "Developed and implemented a new cost control system, reducing project overruns by 20%", "Negotiated contract extensions worth $5M with 3 major contractors, ensuring timely project completion"],
    certs: ["MRICS (Member of Royal Institution of Chartered Surveyors)", "CPQS (Certified Professional Quantity Surveyor)", "PRINCE2 Certification", "BIM Certification"],
    mistake: "Including irrelevant certifications not directly related to Quantity Surveying or construction management",
  },
  {
    slug: "solar-energy-engineer", title: "Solar Energy Engineer", category: "Engineering",
    salary: "$80,000 - $120,000 per year (SAR 300,000 - SAR 450,000)",
    demand: "High demand driven by Saudi Vision 2030's renewable energy targets, aiming for 50% of electricity from renewables by 2030.",
    atsKeywords: ["Solar Energy Engineer", "PV System Design", "SolarCAD", "Autodesk", "Renewable Energy", "Energy Efficiency", "Electrical Engineering", "Grid Connection", "Solar Inverters", "Energy Management Systems"],
    skills: ["Electrical Engineering", "Project Management", "Data Analysis", "Communication", "Problem-Solving", "Team Leadership", "CAD Design"],
    summary: "Results-driven Solar Energy Engineer with 8 years of experience, delivering projects with up to 25% above projected energy output. Proven track record in designing and implementing efficient solar energy systems globally.",
    bullets: ["Designed and implemented a 5MW solar farm in KSA, achieving 98% efficiency rate and saving $1.2M in annual energy costs.", "Led a team of 10 engineers to complete 20 residential solar projects within 6 months, 2 weeks ahead of schedule.", "Conducted energy audits for 50 commercial buildings, identifying potential for 3MW of solar energy integration."],
    certs: ["Professional Engineer (PE) License", "Certified Solar Energy Engineer (CSEE)", "OSHA Certification", "Autodesk CAD Certification"],
    mistake: "Including irrelevant technical skills not directly applicable to solar energy engineering, distracting from core competencies.",
  },
  {
    slug: "nurse-practitioner", title: "Nurse Practitioner", category: "Healthcare",
    salary: "$85,000 - $110,000 USD per year (SAR 319,250 - SAR 413,000 per year)",
    demand: "High demand for Nurse Practitioners in KSA, aligned with Saudi Vision 2030's healthcare expansion goals.",
    atsKeywords: ["Electronic Health Records (EHRs)", "Medicare Billing", "Nurse Practitioner Certification", "Clinical Decision Support Systems", "Telehealth Platforms", "ICU Experience", "Primary Care Management", "EMR Optimization"],
    skills: ["Critical Care Nursing", "Patient Assessment", "Cultural Competence", "Leadership", "EMR Management", "Pharmacology", "Interpersonal Communication"],
    summary: "Dedicated Nurse Practitioner with 8+ years of experience, achieving a 25% patient satisfaction rate increase through personalized care plans. Proficient in managing chronic conditions in diverse populations.",
    bullets: ["Managed a caseload of 120 patients/month in a busy primary care setting, reducing wait times by 30% through process optimization.", "Collaborated with physicians to develop and implement care protocols, resulting in a 20% decrease in hospital readmissions.", "Utilized EHRs to track patient outcomes, identifying trends that informed evidence-based practice changes, improving patient retention by 18%."],
    certs: ["Certified Nurse Practitioner (CNP)", "Basic Life Support (BLS) Certification", "Advanced Cardiovascular Life Support (ACLS)", "Certified Diabetes Educator (CDE)"],
    mistake: "Failing to quantify patient outcomes and impact of care in work experience sections.",
  },
  {
    slug: "dentist", title: "Dentist", category: "Healthcare",
    salary: "$120,000 - $250,000 (SAR 450,000 - 937,500) annually",
    demand: "High demand in KSA, aligned with Saudi Vision 2030's healthcare expansion goals",
    atsKeywords: ["DDS", "Dental Surgery", "Orthodontics", "Periodontics", "Dental Implants", "CEREC", "Digital Radiography", "Invisalign"],
    skills: ["Clinical Dentistry", "Patient Communication", "Time Management", "Dental Software", "Team Leadership", "Anesthesia Administration", "Restorative Procedures"],
    summary: "Dedicated Dentist with 8+ years of experience, delivering 95%+ patient satisfaction rates. Proficient in general and specialized dental procedures",
    bullets: ["Performed 500+ successful dental implants with 98% success rate", "Managed a team of 5 hygienists, increasing productivity by 30%", "Reduced patient wait times by 40% through efficient scheduling"],
    certs: ["DDS (Doctor of Dental Surgery)", "Saudi Commission for Health Specialties (SCFHS) License", "Certified Dental Implantologist (CDI)", "American Board of General Dentistry (ABGD)"],
    mistake: "Including irrelevant hobbies (e.g., 'hiking') without highlighting transferable skills",
  },
  {
    slug: "cloud-architect", title: "Cloud Architect", category: "Technology",
    salary: "$140,000 - $220,000 per year (SAR 525,000 - 825,000)",
    demand: "High demand driven by Saudi Vision 2030's digital transformation initiatives.",
    atsKeywords: ["AWS Certified Solutions Architect", "Azure Architecture", "Google Cloud Platform", "Cloud Security", "DevOps", "Containerization", "Kubernetes", "CI/CD Pipelines"],
    skills: ["Cloud Migration", "Security Compliance", "Team Leadership", "Communication", "Problem Solving", "Agile Methodologies", "Cost Optimization"],
    summary: "Transformational Cloud Architect with 10+ years of experience, delivering cloud infrastructure that reduces costs by up to 30% and boosts scalability. Proven track record of leading cross-functional teams through successful cloud migrations.",
    bullets: ["Designed and implemented a hybrid cloud architecture for a Fortune 500 company, resulting in 25% increased efficiency.", "Led a team of 8 engineers in migrating 120 on-premise applications to AWS, achieving 99.99% uptime.", "Developed and enforced cloud security policies, reducing vulnerabilities by 40% across the organization."],
    certs: ["AWS Certified Solutions Architect - Professional", "Microsoft Certified: Azure Architect Expert", "Google Cloud Certified - Professional Cloud Architect"],
    mistake: "Overemphasizing technical jargon without providing quantifiable achievements in cloud architecture and migration projects.",
  },
  {
    slug: "warehouse-supervisor", title: "Warehouse Supervisor", category: "Business",
    salary: "$60,000 - $90,000 per year (SAR 225,000 - 337,500/year)",
    demand: "High demand in KSA due to logistics growth aligned with Saudi Vision 2030’s industrialization goals.",
    atsKeywords: ["Warehouse Management Software", "Supply Chain Optimization", "Inventory Control Systems", "Forklift Operations", "Warehouse Safety Protocols", "Team Leadership", "KPI Analysis"],
    skills: ["Operational Planning", "Inventory Management", "Leadership", "Communication", "Problem-Solving", "Basic Accounting", "MS Office Suite"],
    summary: "Results-driven Warehouse Supervisor with 8+ years of experience, achieving a 25% reduction in operational costs through process improvements. Proven track record of increasing team productivity by 30% through effective leadership.",
    bullets: ["Managed a team of 15, reducing inventory discrepancies by 20% through strict cycle count implementation.", "Implemented a new receiving process, cutting unloading times by 40% and increasing overall warehouse efficiency.", "Achieved OSHA certification, maintaining a zero-accident record for 3 consecutive years."],
    certs: ["OSHA Certification", "APICS Certified Supply Chain Professional (CSCP)", "Forklift Operator Certification", "Warehouse Management Certification (WMC)"],
    mistake: "Failing to quantify achievements in the work experience section, e.g., not specifying percentage improvements or team sizes.",
  },
  {
    slug: "truck-driver", title: "Truck Driver", category: "Business",
    salary: "$50,000 - $80,000 (SAR 187,500 - SAR 300,000) annually",
    demand: "High demand for experienced Truck Drivers in KSA, aligned with Saudi Vision 2030's logistics and transportation development goals.",
    atsKeywords: ["CDL License", "Trucking Software", "Logistics Management", "Fleet Management", "Hazardous Materials", "Cargo Security", "Route Optimization"],
    skills: ["Commercial Driving", "Route Planning", "Time Management", "Customer Service", "Mechanical Aptitude", "Team Collaboration", "Adaptability"],
    summary: "Seasoned Truck Driver with 8+ years of experience, achieving a 99.9% on-time delivery rate across 500,000+ miles driven. Proven track record of safe driving with zero accidents.",
    bullets: ["Driven over 120,000 miles annually for 5 years with a perfect safety record.", "Successfully managed and delivered oversized cargo to 20+ construction sites within tight deadlines.", "Improved route efficiency by 15% through optimized planning, reducing fuel consumption."],
    certs: ["Commercial Driver's License (CDL)", "Hazardous Materials Endorsement", "First Aid & CPR Certification", "Defensive Driving Course"],
    mistake: "Failing to quantify driving experience in miles and safety record.",
  },
  {
    slug: "electrician", title: "Electrician", category: "Trades",
    salary: "SAR 60,000 - 120,000 per year (approx. USD 16,000 - 32,000)",
    demand: "High demand in KSA driven by infrastructure projects aligned with Saudi Vision 2030",
    atsKeywords: ["Electrical Wiring", "Circuit Analysis", "NEC Codes", "Troubleshooting", "HVAC Systems", "Electrical Safety", "CAT-5 Cabling", "Solar Panel Installation", "Low Voltage Systems", "Electrical Design"],
    skills: ["Electrical Circuit Analysis", "Troubleshooting", "Team Leadership", "Communication", "Problem Solving", "Time Management", "Adaptability"],
    summary: "Results-driven Electrician with 8+ years of experience, delivering 95%+ project completion rate ahead of schedule. Proficient in electrical system design and implementation.",
    bullets: ["Installed electrical systems in 25 industrial units, reducing project timelines by 20%", "Maintained 99% uptime of electrical infrastructure across 500,000 sq.ft. of commercial space", "Led a team of 5 electricians, achieving a 30% reduction in material waste"],
    certs: ["Licensed Electrician (LE)", "OSHA Certification", "NEC Code Compliance Certificate", "CPR/First Aid Certified"],
    mistake: "Not quantifying experience with specific metrics (e.g., number of projects, size of spaces managed)",
  },
  {
    slug: "content-writer", title: "Content Writer", category: "Marketing",
    salary: "$40,000 - $70,000 per year (SAR 150,000 - SAR 262,500)",
    demand: "High demand for engaging content creators in Saudi Arabia, aligned with Saudi Vision 2030's digital transformation goals.",
    atsKeywords: ["Content Management Systems", "SEO Principles", "Google Analytics", "Content Strategy", "Blog Writing", "Social Media Marketing", "WordPress", "Copy Editing", "Microsoft Office", "Google Suite", "Content Calendar"],
    skills: ["Research Skills", "Creative Writing", "SEO Optimization", "Project Management", "Team Collaboration", "Adaptability", "Data Analysis"],
    summary: "Results-driven Content Writer with 5+ years of experience, boosting engagement by 30% through tailored content strategies. Proficient in crafting compelling copy for diverse audiences.",
    bullets: ["Increased website traffic by 25% through optimized blog posts (avg. 1,500 words/month)", "Developed and executed a social media content calendar, growing followers by 40% in 6 months", "Collaborated with cross-functional teams to launch a campaign, resulting in a 20% increase in sales"],
    certs: ["Certified Content Marketing Professional (CCMP)", "Google Analytics Certification", "HubSpot Content Marketing Certification", "AP Stylebook Certification"],
    mistake: "Including generic, non-quantified statements (e.g., 'Wrote various articles' instead of 'Wrote 20 articles, increasing website traffic by 15%')",
  },
  {
    slug: "social-media-manager", title: "Social Media Manager", category: "Marketing",
    salary: "$50,000 - $80,000 (SAR 187,500 - 300,000) annually",
    demand: "High demand for Social Media Managers in KSA, aligned with Saudi Vision 2030's digital transformation goals.",
    atsKeywords: ["Hootsuite", "Sprout Social", "Facebook Ads Manager", "Twitter Analytics", "Influencer Marketing", "Content Calendar", "SEO Basics", "Google Analytics"],
    skills: ["Digital Content Creation", "Team Leadership", "Data-Driven Decision Making", "Arabic Language", "Crisis Communication", "Adobe Creative Suite", "Google Analytics Certification"],
    summary: "Results-driven Social Media Manager with 5+ years of experience, boosting engagement by 300% through targeted campaigns. Proven track record of increasing brand followers by 50% in 6 months.",
    bullets: ["Increased Instagram followers by 40% in 3 months with themed content campaigns.", "Managed a team of 3, resulting in a 25% increase in social media-driven website traffic.", "Improved Facebook engagement from 1.2% to 3.5% through A/B testing and optimized ad spend."],
    certs: ["Google Analytics Certification", "Hootsuite Social Media Marketing Certification", "HubSpot Inbound Marketing Certification", "Facebook Blueprint Certification"],
    mistake: "Not quantifying the impact of social media campaigns in the work experience section.",
  },
  {
    slug: "recruiter", title: "Recruiter", category: "Business",
    salary: "$50,000 - $80,000 per year (SAR 187,500 - 300,000)",
    demand: "High demand in KSA due to Saudi Vision 2030 driving business growth and talent acquisition needs.",
    atsKeywords: ["ATS Software", "Recruitment Marketing", "Sourcing Strategies", "HRIS Systems", "Talent Pipelining", "Employer Branding", "Diversity Hiring", "Metrics Analysis", "Interview Coordination", "Candidate Management"],
    skills: ["Strategic Sourcing", "Communication", "Project Management", "Data Analysis", "Team Leadership", "Digital Recruitment Tools", "Cultural Fit Assessment"],
    summary: "Results-driven Recruiter with 5+ years of experience, delivering a 30% reduction in time-to-hire through optimized sourcing strategies. Proven track record of achieving 95% client satisfaction ratings.",
    bullets: ["Reduced average time-to-hire by 40% within 6 months through process streamlining.", "Successfully managed a portfolio of 50+ open positions, achieving a 98% fill rate.", "Implemented a diversity hiring initiative, increasing underrepresented group placements by 25%."],
    certs: ["SHRM Certified Professional (SHRM-CP)", "Certified Recruiter (CR)", "Google Analytics Certification"],
    mistake: "Failing to quantify achievements in the work experience section.",
  },
];

export const JOB_SLUGS = JOBS.map((j) => j.slug);
export const getJob = (slug: string) => JOBS.find((j) => j.slug === slug);
export const CATEGORIES = Array.from(new Set(JOBS.map((j) => j.category)));
